# Generated by Django 5.1.3 on 2024-11-24 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=54)),
                ('type', models.CharField(max_length=54)),
                ('price', models.FloatField()),
            ],
        ),
    ]
