# Generated by Django 5.1.3 on 2024-11-24 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_foods_food'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'ordering': ('type',)},
        ),
        migrations.AlterField(
            model_name='food',
            name='id',
            field=models.IntegerField(db_index=True, primary_key=True, serialize=False),
        ),
    ]
